DROP TABLE IF EXISTS Admin;

CREATE TABLE Admin (
  PortalID 		INT(10) UNSIGNED DEFAULT '0' NOT NULL,
  Name 			VARCHAR(80) DEFAULT '' NOT NULL,
  Authority		VARCHAR(80) DEFAULT '' NOT NULL,

  PRIMARY KEY (PortalID)
);
