DROP TABLE IF EXISTS User;

CREATE TABLE User (
  GameID 		INT(10) UNSIGNED DEFAULT '0' NOT NULL,
  PortalID 		INT(10) UNSIGNED DEFAULT '0' NOT NULL,
  Name 			VARCHAR(80) DEFAULT '' NOT NULL,
  Race			TINYINT(2) UNSIGNED,
  CreateTime 	INT(10) UNSIGNED DEFAULT '0',
  LastLogin 	INT(10) UNSIGNED DEFAULT '0',
  Server 		INT(10) UNSIGNED DEFAULT '0',

  PRIMARY KEY (GameID),
  UNIQUE idx0 (PortalID)
);
